image: python:3.7

variables:
  UPTIMEROBOT_API: $CI_API_KEY
  UPTIMEROBOT_CONTACTS: $CI_ALERT_CONTACTS
  UPTIMEROBOT_LOGS: 0
  UPTIMEROBOT_OUTPUT: json

stages:
  - test
  - analysis
  - coverage

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - date
    - python -m unittest -v
    - date

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: ${SONAR_URL}
    SONAR_ANALYSIS_MODE: issues
  script:
  - gitlab-sonar-scanner -Dsonar.login=$SONAR_LOGIN

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: ${SONAR_URL}
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner -Dsonar.login=$SONAR_LOGIN

coverage:
  stage: coverage
  script:
    - date
    - pip install coverage codecov
    - date
    - coverage run -m unittest -v
    - date
    - coverage report --omit=tests.py
    - codecov --token=$CODECOV_TOKEN
  allow_failure: true
